name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: "30 18 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_LANGUAGE: "False"
          SHOW_TIMEZONE: "True"
          SHOW_EDITORS: "False"
          SHOW_DURATION: "False"
          SHOW_COMMIT: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_RANK: "False"
          SHOW_GRAPHS: "False"
          SHOW_LANGUAGE_PERCENT: "False"
          SHOW_OS_PERCENT: "False"
          SHOW_PROJECT_PERCENT: "False"
          SHOW_COMMIT_PERCENT: "False"
          SHOW_LINES_OF_CODE_PERCENT: "False"
          SHOW_DURATION_PERCENT: "False"
          SHOW_RANK_PERCENT: "False"
          SHOW_GRAPHS_PERCENT: "False"
          SHOW_TIMEZONE_PERCENT: "False"
          SHOW_EDITORS_PERCENT: "False"
          SHOW_LANGUAGE_COLOR: "False"
          SHOW_LANGUAGE_TEXT: "False"
          SHOW_LANGUAGE_TEXT_PERCENT: "False"
          SHOW_LANGUAGE_COLOR_PERCENT: "False"
          SHOW_OS_COLOR: "False"
          SHOW_OS_TEXT: "False"
          SHOW_OS_TEXT_PERCENT: "False"
          SHOW_OS_COLOR_PERCENT: "False"
          SHOW_PROJECT_COLOR: "False"
          SHOW_PROJECT_TEXT: "False"
          SHOW_PROJECT_TEXT_PERCENT: "False"
          SHOW_PROJECT_COLOR_PERCENT: "False"
          SHOW_COMMIT_COLOR: "False"
          SHOW_COMMIT_TEXT: "False"
          SHOW_COMMIT_TEXT_PERCENT: "False"
          SHOW_COMMIT_COLOR_PERCENT: "False"
          SHOW_LINES_OF_CODE_COLOR: "False"
          SHOW_LINES_OF_CODE_TEXT: "False"
          SHOW_LINES_OF_CODE_TEXT_PERCENT: "False"
          SHOW_LINES_OF_CODE_COLOR_PERCENT: "False"
          SHOW_DURATION_COLOR: "False"
          SHOW_DURATION_TEXT: "False"
          SHOW_DURATION_TEXT_PERCENT: "False"
          SHOW_DURATION_COLOR_PERCENT: "False"
          SHOW_RANK_COLOR: "False"
          SHOW_RANK_TEXT: "False"
          SHOW_RANK_TEXT_PERCENT: "False"
          SHOW_RANK_COLOR_PERCENT: "False"
          SHOW_TIMEZONE_COLOR: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_OS: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "True"
          SHOW_LOC_CHART_PERCENT: "False"
          SHOW_LOC_CHART_COLOR: "False"
          SHOW_LOC_CHART_TEXT: "False"
          SHOW_LOC_CHART_TEXT_PERCENT: "False"
          SHOW_LOC_CHART_COLOR_PERCENT: "False"
          SHOW_LOC_CHART_PERCENT: "False"
          SHOW_LOC_CHART_COLOR: "False"
          SHOW_LOC_CHART_TEXT: "False"
